name: Generate Dist File for Plugin
on:
  push:
    tags:
     - '*'
   # branches:
   # - main
      
permissions:
  contents: write

jobs:
  generate-json-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Run WP Self-Host Update JSON Generator
        uses: escii/wp-self-host-updater-generator@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
